### ISSUE TITLE
DCOS CLuster is "oauth_enabled: false" ,How can I run  ?

### ISSUE THREAD

**Issue by gl328518397** [mesosphere/marathon-autoscale#9]
my DCOS CLuster is "oauth_enabled: false".
when I run "python marathon-autoscale.py "  IT  have some err:
![qq 20170222102924](https://cloud.githubusercontent.com/assets/14244945/23194566/d12194b2-f8e9-11e6-9705-4a62f0752265.png)

**Comment by gl328518397** [comment]
can i  ignore the check below:  
"   Enter the username for the DCOS cluster : " 
"   Enter the password for the DCOS cluster : "

**Comment by gl328518397** [comment]
Someone else meet the same question ?

**Comment by tkrausjr** [comment]
I have a pull request which might address this but its going to change how you run this script and you should be able to run as docker container or in a shell.

**Comment by gl328518397** [comment]
Thank you ,I will try。
